-- publishers
INSERT INTO publishers(publisher_id,name) values (1,'O''Reilly Media');
INSERT INTO publishers(publisher_id,name) values (2,'A Book Apart');
INSERT INTO publishers(publisher_id,name) values (3,'A K PETERS');
INSERT INTO publishers(publisher_id,name) values (4,'Academic Press');
INSERT INTO publishers(publisher_id,name) values (5,'Addison Wesley');
INSERT INTO publishers(publisher_id,name) values (10,'Albert&Sweigart');
INSERT INTO publishers(publisher_id,name) values (11,'Alfred A. Knopf');
INSERT INTO publishers(publisher_id,name) values (12,'AMACOM');
INSERT INTO publishers(publisher_id,name) values (13,'AMLbook.com');
INSERT INTO publishers(publisher_id,name) values (14,'Apress');
INSERT INTO publishers(publisher_id,name) values (15,'Arpaci-Dusseau Books');
INSERT INTO publishers(publisher_id,name) values (16,'Artima');
INSERT INTO publishers(publisher_id,name) values (17,'Atlantic Monthly Press');
INSERT INTO publishers(publisher_id,name) values (18,'Attribution-ShareAlike License');
INSERT INTO publishers(publisher_id,name) values (19,'Avon');
INSERT INTO publishers(publisher_id,name) values (20,'Back Bay Books');
INSERT INTO publishers(publisher_id,name) values (21,'Bantam');
INSERT INTO publishers(publisher_id,name) values (23,'Bartlett Publishing');
INSERT INTO publishers(publisher_id,name) values (24,'Basic Books');
INSERT INTO publishers(publisher_id,name) values (25,'Berkley Trade');
INSERT INTO publishers(publisher_id,name) values (26,'Big Machine');
INSERT INTO publishers(publisher_id,name) values (27,'Big Nerd Ranch Guides');
INSERT INTO publishers(publisher_id,name) values (28,'Bloomsbury (NYC)');
INSERT INTO publishers(publisher_id,name) values (29,'Blue Hole Press');
INSERT INTO publishers(publisher_id,name) values (30,'Blue Windmill Media');
INSERT INTO publishers(publisher_id,name) values (31,'BPB Publications');
INSERT INTO publishers(publisher_id,name) values (32,'Bradford Book');
INSERT INTO publishers(publisher_id,name) values (33,'Brooks Cole');
INSERT INTO publishers(publisher_id,name) values (34,'Cambridge University Press');
INSERT INTO publishers(publisher_id,name) values (35,'Careermonk Publications');
INSERT INTO publishers(publisher_id,name) values (36,'Carnegie Mellon University');
INSERT INTO publishers(publisher_id,name) values (37,'Cartwheel Web');
INSERT INTO publishers(publisher_id,name) values (38,'Celeritas Publishing');
INSERT INTO publishers(publisher_id,name) values (39,'Cengage Learning');
INSERT INTO publishers(publisher_id,name) values (40,'Center for the Study of Language and Inf');
INSERT INTO publishers(publisher_id,name) values (41,'Chapman & Hall/CRC');
INSERT INTO publishers(publisher_id,name) values (42,'Chelsea Green Publishing');
INSERT INTO publishers(publisher_id,name) values (43,'Clarendon Press');
INSERT INTO publishers(publisher_id,name) values (44,'Code Energy LLC');
INSERT INTO publishers(publisher_id,name) values (45,'College Publications');
INSERT INTO publishers(publisher_id,name) values (46,'Copernicus Books');
INSERT INTO publishers(publisher_id,name) values (47,'Coriolis Group,U.S.');
INSERT INTO publishers(publisher_id,name) values (48,'Course Technology');
INSERT INTO publishers(publisher_id,name) values (50,'CRC Press');
INSERT INTO publishers(publisher_id,name) values (51,'createspace');
INSERT INTO publishers(publisher_id,name) values (52,'Createspace Independent Publishing Platform');
INSERT INTO publishers(publisher_id,name) values (53,'Creative Commons 3.0');
INSERT INTO publishers(publisher_id,name) values (54,'Creston Books');
INSERT INTO publishers(publisher_id,name) values (55,'Critical Connection');
INSERT INTO publishers(publisher_id,name) values (56,'Crown');
INSERT INTO publishers(publisher_id,name) values (57,'Crown Business');
INSERT INTO publishers(publisher_id,name) values (58,'Crown Publishing, NY');
INSERT INTO publishers(publisher_id,name) values (59,'Currency');
INSERT INTO publishers(publisher_id,name) values (60,'Current');
INSERT INTO publishers(publisher_id,name) values (61,'Dan Bader');
INSERT INTO publishers(publisher_id,name) values (62,'Delta');
INSERT INTO publishers(publisher_id,name) values (63,'Dey Street Books');
INSERT INTO publishers(publisher_id,name) values (64,'Digital Press');
INSERT INTO publishers(publisher_id,name) values (65,'Dorset House');
INSERT INTO publishers(publisher_id,name) values (66,'Dorset House Publishing Company, Incorporated');
INSERT INTO publishers(publisher_id,name) values (67,'Doubleday');
INSERT INTO publishers(publisher_id,name) values (68,'Dover Publications');
INSERT INTO publishers(publisher_id,name) values (69,'Dymaxicon');
INSERT INTO publishers(publisher_id,name) values (70,'Ecco');
INSERT INTO publishers(publisher_id,name) values (71,'Edinburgh University Press');
INSERT INTO publishers(publisher_id,name) values (72,'Effective Bookshelf');
INSERT INTO publishers(publisher_id,name) values (73,'Elsevier Science & Technology');
INSERT INTO publishers(publisher_id,name) values (74,'Feisty Duck Ltd');
INSERT INTO publishers(publisher_id,name) values (75,'Feiwel & Friends');
INSERT INTO publishers(publisher_id,name) values (76,'For Dummies');
INSERT INTO publishers(publisher_id,name) values (77,'Franklin Beedle & Associates');
INSERT INTO publishers(publisher_id,name) values (78,'Free Press');
INSERT INTO publishers(publisher_id,name) values (79,'Free Software Foundation');
INSERT INTO publishers(publisher_id,name) values (80,'Friends of ED');
INSERT INTO publishers(publisher_id,name) values (81,'Gallery Books');
INSERT INTO publishers(publisher_id,name) values (82,'General Systemantics Press');
INSERT INTO publishers(publisher_id,name) values (83,'Genever Benning');
INSERT INTO publishers(publisher_id,name) values (84,'Graphics Press');
INSERT INTO publishers(publisher_id,name) values (85,'Green Tea Press');
INSERT INTO publishers(publisher_id,name) values (86,'Gumroad');
INSERT INTO publishers(publisher_id,name) values (87,'Hachette Books');
INSERT INTO publishers(publisher_id,name) values (88,'Harper');
INSERT INTO publishers(publisher_id,name) values (91,'Harvard Business Review Press');
INSERT INTO publishers(publisher_id,name) values (92,'Harvard University Press');
INSERT INTO publishers(publisher_id,name) values (93,'Houghton Mifflin Harcourt');
INSERT INTO publishers(publisher_id,name) values (94,'Hyperink');
INSERT INTO publishers(publisher_id,name) values (95,'IDG Books Worldwide, Inc.');
INSERT INTO publishers(publisher_id,name) values (96,'Indianapolis');
INSERT INTO publishers(publisher_id,name) values (97,'It Revolution Press');
INSERT INTO publishers(publisher_id,name) values (98,'John C. Scott');
INSERT INTO publishers(publisher_id,name) values (99,'John Murray');
INSERT INTO publishers(publisher_id,name) values (100,'John Wiley & Sons');
INSERT INTO publishers(publisher_id,name) values (101,'Jones & Bartlett Publishers');
INSERT INTO publishers(publisher_id,name) values (102,'Kate Thompson');
INSERT INTO publishers(publisher_id,name) values (103,'Knopf');
INSERT INTO publishers(publisher_id,name) values (104,'Knopf Doubleday Publishing Group');
INSERT INTO publishers(publisher_id,name) values (105,'Leanpub');
INSERT INTO publishers(publisher_id,name) values (106,'Little, Brown and Company');
INSERT INTO publishers(publisher_id,name) values (107,'Lulu');
INSERT INTO publishers(publisher_id,name) values (109,'Machine Intelligence Research Institute');
INSERT INTO publishers(publisher_id,name) values (110,'Maker Media, Inc');
INSERT INTO publishers(publisher_id,name) values (111,'Manning');
INSERT INTO publishers(publisher_id,name) values (115,'Markus Winand (2012)');
INSERT INTO publishers(publisher_id,name) values (116,'Marshall & Brainerd');
INSERT INTO publishers(publisher_id,name) values (117,'MCD');
INSERT INTO publishers(publisher_id,name) values (119,'McGraw-Hill');
INSERT INTO publishers(publisher_id,name) values (126,'Merkle Bloom LLC');
INSERT INTO publishers(publisher_id,name) values (127,'Metropolitan Books/Henry Holt (NY)');
INSERT INTO publishers(publisher_id,name) values (128,'Microsoft Press');
INSERT INTO publishers(publisher_id,name) values (129,'MIT');
INSERT INTO publishers(publisher_id,name) values (133,'Morgan Kaufmann Publishers');
INSERT INTO publishers(publisher_id,name) values (134,'MSAC Philosophy Group');
INSERT INTO publishers(publisher_id,name) values (136,'New Riders Publishing');
INSERT INTO publishers(publisher_id,name) values (137,'New York University Press');
INSERT INTO publishers(publisher_id,name) values (138,'Nmap Project');
INSERT INTO publishers(publisher_id,name) values (139,'No Starch Press');
INSERT INTO publishers(publisher_id,name) values (141,'Off-By-One Press');
INSERT INTO publishers(publisher_id,name) values (143,'OR Books');
INSERT INTO publishers(publisher_id,name) values (148,'OUP Oxford');
INSERT INTO publishers(publisher_id,name) values (149,'Oxford University Press (UK)');
INSERT INTO publishers(publisher_id,name) values (150,'Oxford University Press, USA');
INSERT INTO publishers(publisher_id,name) values (151,'P&R Publishing');
INSERT INTO publishers(publisher_id,name) values (152,'Packt Publishing');
INSERT INTO publishers(publisher_id,name) values (154,'Pantheon');
INSERT INTO publishers(publisher_id,name) values (155,'Paraglyph Press');
INSERT INTO publishers(publisher_id,name) values (156,'Peachpit Press');
INSERT INTO publishers(publisher_id,name) values (157,'Pearson');
INSERT INTO publishers(publisher_id,name) values (158,'Pearson Prentice Hall');
INSERT INTO publishers(publisher_id,name) values (159,'Peer-To-Peer Communications');
INSERT INTO publishers(publisher_id,name) values (160,'Penguin');
INSERT INTO publishers(publisher_id,name) values (164,'Plume');
INSERT INTO publishers(publisher_id,name) values (165,'Portfolio');
INSERT INTO publishers(publisher_id,name) values (166,'Portfolio Hardcover');
INSERT INTO publishers(publisher_id,name) values (167,'Pragmatic Bookshelf');
INSERT INTO publishers(publisher_id,name) values (168,'Praxis Publications Inc');
INSERT INTO publishers(publisher_id,name) values (169,'Prentice Hall');
INSERT INTO publishers(publisher_id,name) values (173,'Princeton Architectural Press');
INSERT INTO publishers(publisher_id,name) values (174,'Princeton University Press');
INSERT INTO publishers(publisher_id,name) values (175,'PublicAffairs');
INSERT INTO publishers(publisher_id,name) values (176,'Punchy Publishing');
INSERT INTO publishers(publisher_id,name) values (177,'Pyrenean Gold Press');
INSERT INTO publishers(publisher_id,name) values (179,'Que Publishing');
INSERT INTO publishers(publisher_id,name) values (180,'Random House Audio Publishing Group');
INSERT INTO publishers(publisher_id,name) values (181,'Random House Trade Paperbacks');
INSERT INTO publishers(publisher_id,name) values (182,'Recursive Books');
INSERT INTO publishers(publisher_id,name) values (183,'Rockport Publishers');
INSERT INTO publishers(publisher_id,name) values (184,'Rosenfeld Media');
INSERT INTO publishers(publisher_id,name) values (186,'Sams Publishing');
INSERT INTO publishers(publisher_id,name) values (187,'Scribner');
INSERT INTO publishers(publisher_id,name) values (188,'Self');
INSERT INTO publishers(publisher_id,name) values (190,'Simon & Schuster');
INSERT INTO publishers(publisher_id,name) values (192,'Simple Programmer');
INSERT INTO publishers(publisher_id,name) values (193,'SitePoint');
INSERT INTO publishers(publisher_id,name) values (194,'Society for Industrial and Applied Mathematics (SIAM)');
INSERT INTO publishers(publisher_id,name) values (195,'Soundlikeyourself Publishing, LLC');
INSERT INTO publishers(publisher_id,name) values (196,'Sourcebooks');
INSERT INTO publishers(publisher_id,name) values (197,'Spectra');
INSERT INTO publishers(publisher_id,name) values (198,'Spektrum Akademischer Verlag');
INSERT INTO publishers(publisher_id,name) values (199,'Springer');
INSERT INTO publishers(publisher_id,name) values (200,'St. Martin''s Griffin');
INSERT INTO publishers(publisher_id,name) values (201,'St. Martin''s Press');
INSERT INTO publishers(publisher_id,name) values (202,'Syngress');
INSERT INTO publishers(publisher_id,name) values (203,'Syngress Publishing');
INSERT INTO publishers(publisher_id,name) values (204,'The MIT Press');
INSERT INTO publishers(publisher_id,name) values (205,'The Nature of Code');
INSERT INTO publishers(publisher_id,name) values (208,'The Pragmatic Programmers, LLC.');
INSERT INTO publishers(publisher_id,name) values (209,'Thomas Dunne Books/St Martin''s Press (NY)');
INSERT INTO publishers(publisher_id,name) values (210,'Thomson Learning');
INSERT INTO publishers(publisher_id,name) values (211,'Tilted Windmill Press');
INSERT INTO publishers(publisher_id,name) values (212,'Tor Books');
INSERT INTO publishers(publisher_id,name) values (214,'Triangle Connection LLC');
INSERT INTO publishers(publisher_id,name) values (215,'Two Scoops Press');
INSERT INTO publishers(publisher_id,name) values (216,'University of Chicago Press');
INSERT INTO publishers(publisher_id,name) values (217,'University of Illinois Press');
INSERT INTO publishers(publisher_id,name) values (218,'Verso');
INSERT INTO publishers(publisher_id,name) values (220,'Viking Books');
INSERT INTO publishers(publisher_id,name) values (221,'Virgin Books');
INSERT INTO publishers(publisher_id,name) values (222,'W. H. Freeman');
INSERT INTO publishers(publisher_id,name) values (223,'W. W. Norton Company');
INSERT INTO publishers(publisher_id,name) values (226,'W.H. Freeman & Company');
INSERT INTO publishers(publisher_id,name) values (227,'Walker Books');
INSERT INTO publishers(publisher_id,name) values (228,'Waveland Pr Inc');
INSERT INTO publishers(publisher_id,name) values (229,'Wellesley College');
INSERT INTO publishers(publisher_id,name) values (230,'Westview Press');
INSERT INTO publishers(publisher_id,name) values (232,'Wiley Publishing');
INSERT INTO publishers(publisher_id,name) values (233,'Wiley-Interscience');
INSERT INTO publishers(publisher_id,name) values (234,'William Heinemann');
INSERT INTO publishers(publisher_id,name) values (235,'William Morrow');
INSERT INTO publishers(publisher_id,name) values (236,'Wolfram Media');
INSERT INTO publishers(publisher_id,name) values (238,'Wrox Press');
INSERT INTO publishers(publisher_id,name) values (239,'Yahoo Press');
INSERT INTO publishers(publisher_id,name) values (240,'Yaknyam Press');
INSERT INTO publishers(publisher_id,name) values (241,'Yale University Press');